version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - 'postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - demo
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-admin}'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - 'pgadmin:/var/lib/pgadmin'
    ports:
      - '5050:80'
    networks:
      - demo
    restart: unless-stopped
  ota:
    container_name: opentestingapi
    image: ghcr.io/opentestingapi/opentesting:1.37
    ports:
      - '50000:50000'
    network_mode: host
    restart: unless-stopped

networks:
  demo:
    driver: bridge
volumes:
  postgres: null
  pgadmin: null
